import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date

from config.settings import settings
from db.connection import get_session
from db.models import AnalysisSnapshot

logger = logging.getLogger(__name__)


def _build_report(snapshot):
    lines = [
        f"Business Financial Report — {snapshot.snapshot_date}",
        "=" * 50,
        "",
        "SUMMARY",
        "-" * 30,
        f"  Total Revenue:     ${float(snapshot.total_revenue or 0):>12,.2f}",
        f"  Total Expenses:    ${float(snapshot.total_expenses or 0):>12,.2f}",
        f"  Net Profit:        ${float(snapshot.net_profit or 0):>12,.2f}",
        f"  Total Liabilities: ${float(snapshot.total_liabilities or 0):>12,.2f}",
        "",
    ]

    if snapshot.total_revenue and snapshot.net_profit:
        margin = float(snapshot.net_profit) / float(snapshot.total_revenue) * 100
        lines.append(f"  Profit Margin:     {margin:>12.1f}%")
        lines.append("")

    products = snapshot.product_breakdown or []
    if products:
        lines.append("TOP PRODUCTS/SERVICES")
        lines.append("-" * 30)
        for p in products[:10]:
            lines.append(f"  {p['name']}")
            lines.append(f"    Revenue: ${p['total_revenue']:,.2f}  |  Margin: {p['margin_pct']}%  |  Profit: ${p['net_profit']:,.2f}")
        lines.append("")

    insights = snapshot.insights or []
    if insights:
        lines.append("OPTIMIZATION OPPORTUNITIES")
        lines.append("-" * 30)
        for o in insights[:5]:
            lines.append(f"  [{o.get('type', 'general').upper()}] {o.get('suggestion', '')}")
        lines.append("")

    lines.append("---")
    lines.append("Generated by Business Chatbot - Automated Financial Analysis")

    return "\n".join(lines)


def send_report(recipient=None, snapshot_date=None):
    recipient = recipient or settings.REPORT_RECIPIENT
    if not recipient:
        logger.warning("No report recipient configured")
        return

    if not settings.SMTP_USER:
        logger.warning("SMTP not configured, skipping email report")
        return

    with get_session() as session:
        if snapshot_date:
            snapshot = session.query(AnalysisSnapshot).filter_by(snapshot_date=snapshot_date).first()
        else:
            snapshot = session.query(AnalysisSnapshot).order_by(AnalysisSnapshot.snapshot_date.desc()).first()

        if not snapshot:
            logger.warning("No snapshot available for report")
            return

        report_text = _build_report(snapshot)

        msg = MIMEMultipart()
        msg["From"] = settings.SMTP_USER
        msg["To"] = recipient
        msg["Subject"] = f"Business Financial Report — {snapshot.snapshot_date}"
        msg.attach(MIMEText(report_text, "plain"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.send_message(msg)

        logger.info(f"Report sent to {recipient}")
